//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

/// <remarks />
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class Translations
{
    private TranslationsPhrase[] phraseField;

    /// <remarks />
    [XmlElement("Phrase")]
    public TranslationsPhrase[] Phrase
    {
        get { return this.phraseField; }
        set { this.phraseField = value; }
    }
}

/// <remarks />
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType = true)]
public partial class TranslationsPhrase
{
    private string keyField;

    private TranslationsPhraseTranslation[] translationField;

    /// <remarks />
    [XmlElement("Translation")]
    public TranslationsPhraseTranslation[] Translation
    {
        get { return this.translationField; }
        set { this.translationField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public string Key
    {
        get { return this.keyField; }
        set { this.keyField = value; }
    }
}

/// <remarks />
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType = true)]
public partial class TranslationsPhraseTranslation
{
    private string localeField;

    private string valueField;

    /// <remarks />
    [XmlAttribute()]
    public string Locale
    {
        get { return this.localeField; }
        set { this.localeField = value; }
    }

    /// <remarks />
    [XmlText()]
    public string Value
    {
        get { return this.valueField; }
        set { this.valueField = value; }
    }
}