//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

/// <remarks />
[GeneratedCode("xsd", "2.0.50727.42")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlRoot("DPR_Collection", Namespace = "", IsNullable = false)]
public partial class dprcollectiontype
{
    private dprtype[] dPRField;

    /// <remarks />
    [XmlElement("DPR")]
    public dprtype[] DPR
    {
        get { return this.dPRField; }
        set { this.dPRField = value; }
    }
}

/// <remarks />
[GeneratedCode("xsd", "2.0.50727.42")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlRoot("DPR", Namespace = "", IsNullable = false)]
public partial class dprtype
{
    private string attrField;

    private string dField;

    private int dxField;

    private int dyField;

    private string idField;

    private int jstField;

    private int m1Field;

    private int m2Field;

    private string nameField;

    private string pdxField;

    private string pdyField;

    private string propertyField;

    private string pxField;

    private string pyField;

    private string rotField;

    private string typeField;

    private int xField;

    private int yField;

    /// <remarks />
    public string D
    {
        get { return this.dField; }
        set { this.dField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public string name
    {
        get { return this.nameField; }
        set { this.nameField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public string property
    {
        get { return this.propertyField; }
        set { this.propertyField = value; }
    }

    /// <remarks />
    [XmlAttribute(DataType = "positiveInteger")]
    public string id
    {
        get { return this.idField; }
        set { this.idField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int x
    {
        get { return this.xField; }
        set { this.xField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public string px
    {
        get { return this.pxField; }
        set { this.pxField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int y
    {
        get { return this.yField; }
        set { this.yField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public string py
    {
        get { return this.pyField; }
        set { this.pyField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int dx
    {
        get { return this.dxField; }
        set { this.dxField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public string pdx
    {
        get { return this.pdxField; }
        set { this.pdxField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int dy
    {
        get { return this.dyField; }
        set { this.dyField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public string pdy
    {
        get { return this.pdyField; }
        set { this.pdyField = value; }
    }

    /// <remarks />
    [XmlAttribute(DataType = "positiveInteger")]
    public string rot
    {
        get { return this.rotField; }
        set { this.rotField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int jst
    {
        get { return this.jstField; }
        set { this.jstField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public string type
    {
        get { return this.typeField; }
        set { this.typeField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int m1
    {
        get { return this.m1Field; }
        set { this.m1Field = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int m2
    {
        get { return this.m2Field; }
        set { this.m2Field = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public string attr
    {
        get { return this.attrField; }
        set { this.attrField = value; }
    }
}