//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

/// <remarks />
[GeneratedCode("xsd", "2.0.50727.42")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlRoot("DPT_Collection", Namespace = "", IsNullable = false)]
public partial class dptcollectiontype
{
    private dpttype[] dPTField;

    /// <remarks />
    [XmlElement("DPT")]
    public dpttype[] DPT
    {
        get { return this.dPTField; }
        set { this.dPTField = value; }
    }
}

/// <remarks />
[GeneratedCode("xsd", "2.0.50727.42")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlRoot("DPT", Namespace = "", IsNullable = false)]
public partial class dpttype
{
    private int daField;

    private int idField;

    private string nameField;

    private int paField;

    private string valueField;

    /// <remarks />
    [XmlAttribute()]
    public string name
    {
        get { return this.nameField; }
        set { this.nameField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int id
    {
        get { return this.idField; }
        set { this.idField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int t_dim_da
    {
        get { return this.daField; }
        set { this.daField = value; }
    }

    /// <remarks />
    [XmlAttribute()]
    public int t_dim_pa
    {
        get { return this.paField; }
        set { this.paField = value; }
    }

    /// <remarks />
    [XmlText()]
    public string Value
    {
        get { return this.valueField; }
        set { this.valueField = value; }
    }
}