//// ------------------------------------------------------------------------------
////  <auto-generated>
////    Generated by Xsd2Code. Version 3.4.1.34438 Microsoft Reciprocal License (Ms-RL) 
////    <NameSpace>Aristocrat.Monaco.Hardware.Printer</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>True</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
////  </auto-generated>
//// ------------------------------------------------------------------------------
//namespace Aristocrat.Monaco.Hardware.Printer
//{
//    using System;
//    using System.Diagnostics;
//    using System.Xml.Serialization;
//    using System.Collections;
//    using System.Xml.Schema;
//    using System.ComponentModel;


//    /// <content>A dptcollectiontype.</content>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlRootAttribute("DPT_Collection", Namespace = "", IsNullable = false)]
//    public partial class dptcollectiontype
//    {

//        /// <summary>The point field.</summary>
//        private dpttype[] dPTField;

//        /// <summary>Gets or sets the dpt.</summary>
//        /// <value>The dpt.</value>
//        [System.Xml.Serialization.XmlElementAttribute("DPT")]
//        public virtual dpttype[] DPT
//        {
//            get
//            {
//                return this.dPTField;
//            }
//            set
//            {
//                this.dPTField = value;
//            }
//        }
//    }

//    /// <content>A dpttype.</content>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
//    public partial class dpttype
//    {

//        /// <summary>The name field.</summary>
//        private string nameField;

//        /// <summary>The identifier field.</summary>
//        private int idField;

//        /// <summary>The dim da field.</summary>
//        private int t_dim_daField;

//        /// <summary>True if dim da field specified.</summary>
//        private bool t_dim_daFieldSpecified;

//        /// <summary>The dim pa field.</summary>
//        private int t_dim_paField;

//        /// <summary>True if dim pa field specified.</summary>
//        private bool t_dim_paFieldSpecified;

//        /// <summary>The value field.</summary>
//        private string valueField;

//        /// <summary>Initializes a new instance of the Aristocrat.Monaco.Hardware.Printer.dpttype class.</summary>
//        public dpttype()
//        {
//            this.t_dim_daField = 500;
//            this.t_dim_paField = 2020;
//        }

//        /// <summary>Gets or sets the name.</summary>
//        /// <value>The name.</value>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public virtual string name
//        {
//            get
//            {
//                return this.nameField;
//            }
//            set
//            {
//                this.nameField = value;
//            }
//        }

//        /// <summary>Gets or sets the identifier.</summary>
//        /// <value>The identifier.</value>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public virtual int id
//        {
//            get
//            {
//                return this.idField;
//            }
//            set
//            {
//                this.idField = value;
//            }
//        }

//        /// <summary>Gets or sets the dim da.</summary>
//        /// <value>The t dim da.</value>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        [System.ComponentModel.DefaultValueAttribute(500)]
//        public virtual int t_dim_da
//        {
//            get
//            {
//                return this.t_dim_daField;
//            }
//            set
//            {
//                this.t_dim_daField = value;
//            }
//        }

//        /// <summary>Gets or sets a value indicating whether the dim da specified.</summary>
//        /// <value>True if dim da specified, false if not.</value>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public virtual bool t_dim_daSpecified
//        {
//            get
//            {
//                return this.t_dim_daFieldSpecified;
//            }
//            set
//            {
//                this.t_dim_daFieldSpecified = value;
//            }
//        }

//        /// <summary>Gets or sets the dim pa.</summary>
//        /// <value>The t dim pa.</value>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        [System.ComponentModel.DefaultValueAttribute(2020)]
//        public virtual int t_dim_pa
//        {
//            get
//            {
//                return this.t_dim_paField;
//            }
//            set
//            {
//                this.t_dim_paField = value;
//            }
//        }

//        /// <summary>Gets or sets a value indicating whether the dim pa specified.</summary>
//        /// <value>True if dim pa specified, false if not.</value>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public virtual bool t_dim_paSpecified
//        {
//            get
//            {
//                return this.t_dim_paFieldSpecified;
//            }
//            set
//            {
//                this.t_dim_paFieldSpecified = value;
//            }
//        }

//        /// <summary>Gets or sets the value.</summary>
//        /// <value>The value.</value>
//        [System.Xml.Serialization.XmlTextAttribute()]
//        public virtual string Value
//        {
//            get
//            {
//                return this.valueField;
//            }
//            set
//            {
//                this.valueField = value;
//            }
//        }
//    }
//}
