//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
//
#pragma warning disable CS1591
namespace Aristocrat.Monaco.Accounting.Contracts {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccountingConfiguration {
        
        private AccountingConfigurationMoneyLaunderingMonitor moneyLaunderingMonitorField;
        
        private AccountingConfigurationTenderIn tenderInField;
        
        private AccountingConfigurationCreditLimits creditLimitsField;
        
        private AccountingConfigurationWinLimits winLimitsField;
        
        private AccountingConfigurationNoteIn noteInField;
        
        private AccountingConfigurationVoucherIn voucherInField;
        
        private AccountingConfigurationVoucherOut voucherOutField;
        
        private AccountingConfigurationRebootWhilePrinting rebootWhilePrintingField;
        
        private AccountingConfigurationReprintLoggedVoucher reprintLoggedVoucherField;
        
        private AccountingConfigurationHandpay handpayField;
        
        private AccountingConfigurationHandCount handCountField;
        
        private AccountingConfigurationMysteryProgressive mysteryProgressiveField;
        
        private AccountingConfigurationCashoutOnCarrierBoardRemoval cashoutOnCarrierBoardRemovalField;
        
        private AccountingConfigurationNoteAcceptorTimeLimit noteAcceptorTimeLimitField;
        
        private AccountingConfigurationBillClearance billClearanceField;
        
        private AccountingConfigurationTestTicket testTicketField;
        
        /// <remarks/>
        public AccountingConfigurationMoneyLaunderingMonitor MoneyLaunderingMonitor {
            get {
                return this.moneyLaunderingMonitorField;
            }
            set {
                this.moneyLaunderingMonitorField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationTenderIn TenderIn {
            get {
                return this.tenderInField;
            }
            set {
                this.tenderInField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationCreditLimits CreditLimits {
            get {
                return this.creditLimitsField;
            }
            set {
                this.creditLimitsField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationWinLimits WinLimits {
            get {
                return this.winLimitsField;
            }
            set {
                this.winLimitsField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationNoteIn NoteIn {
            get {
                return this.noteInField;
            }
            set {
                this.noteInField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationVoucherIn VoucherIn {
            get {
                return this.voucherInField;
            }
            set {
                this.voucherInField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationVoucherOut VoucherOut {
            get {
                return this.voucherOutField;
            }
            set {
                this.voucherOutField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationRebootWhilePrinting RebootWhilePrinting {
            get {
                return this.rebootWhilePrintingField;
            }
            set {
                this.rebootWhilePrintingField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationReprintLoggedVoucher ReprintLoggedVoucher {
            get {
                return this.reprintLoggedVoucherField;
            }
            set {
                this.reprintLoggedVoucherField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationHandpay Handpay {
            get {
                return this.handpayField;
            }
            set {
                this.handpayField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationHandCount HandCount {
            get {
                return this.handCountField;
            }
            set {
                this.handCountField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationMysteryProgressive MysteryProgressive {
            get {
                return this.mysteryProgressiveField;
            }
            set {
                this.mysteryProgressiveField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationCashoutOnCarrierBoardRemoval CashoutOnCarrierBoardRemoval {
            get {
                return this.cashoutOnCarrierBoardRemovalField;
            }
            set {
                this.cashoutOnCarrierBoardRemovalField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationNoteAcceptorTimeLimit NoteAcceptorTimeLimit {
            get {
                return this.noteAcceptorTimeLimitField;
            }
            set {
                this.noteAcceptorTimeLimitField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationBillClearance BillClearance {
            get {
                return this.billClearanceField;
            }
            set {
                this.billClearanceField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationTestTicket TestTicket {
            get {
                return this.testTicketField;
            }
            set {
                this.testTicketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationMoneyLaunderingMonitor {
        
        private bool enabledField;
        
        private bool visibleField;
        
        private string soundFilePathField;
        
        public AccountingConfigurationMoneyLaunderingMonitor() {
            this.enabledField = false;
            this.visibleField = false;
            this.soundFilePathField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string SoundFilePath {
            get {
                return this.soundFilePathField;
            }
            set {
                this.soundFilePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationTenderIn {
        
        private AccountingConfigurationTenderInMaxCreditsIn maxCreditsInField;
        
        private bool checkLaundryLimitField;
        
        private long maxTenderInLimitField;
        
        private CheckCreditsStrategy checkCreditsInField;
        
        private bool allowCreditUnderLimitField;
        
        private long creditLimitField;
        
        private bool creditLimitFieldSpecified;
        
        public AccountingConfigurationTenderIn() {
            this.checkLaundryLimitField = false;
            this.maxTenderInLimitField = ((long)(300000000));
            this.checkCreditsInField = CheckCreditsStrategy.None;
            this.allowCreditUnderLimitField = false;
        }
        
        /// <remarks/>
        public AccountingConfigurationTenderInMaxCreditsIn MaxCreditsIn {
            get {
                return this.maxCreditsInField;
            }
            set {
                this.maxCreditsInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CheckLaundryLimit {
            get {
                return this.checkLaundryLimitField;
            }
            set {
                this.checkLaundryLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "300000000")]
        public long MaxTenderInLimit {
            get {
                return this.maxTenderInLimitField;
            }
            set {
                this.maxTenderInLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CheckCreditsStrategy.None)]
        public CheckCreditsStrategy CheckCreditsIn {
            get {
                return this.checkCreditsInField;
            }
            set {
                this.checkCreditsInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AllowCreditUnderLimit {
            get {
                return this.allowCreditUnderLimitField;
            }
            set {
                this.allowCreditUnderLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long CreditLimit {
            get {
                return this.creditLimitField;
            }
            set {
                this.creditLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreditLimitSpecified {
            get {
                return this.creditLimitFieldSpecified;
            }
            set {
                this.creditLimitFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationTenderInMaxCreditsIn {
        
        private long defaultField;
        
        private bool editableField;
        
        public AccountingConfigurationTenderInMaxCreditsIn() {
            this.defaultField = ((long)(10000000000));
            this.editableField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "10000000000")]
        public long Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum CheckCreditsStrategy {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Balance,
        
        /// <remarks/>
        Session,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationCreditLimits {
        
        private AccountingConfigurationCreditLimitsMaxCreditMeter maxCreditMeterField;
        
        private AccountingConfigurationCreditLimitsMaxBetLimit maxBetLimitField;
        
        private bool allowCreditsInAboveMaxCreditField;
        
        public AccountingConfigurationCreditLimits() {
            this.allowCreditsInAboveMaxCreditField = false;
        }
        
        /// <remarks/>
        public AccountingConfigurationCreditLimitsMaxCreditMeter MaxCreditMeter {
            get {
                return this.maxCreditMeterField;
            }
            set {
                this.maxCreditMeterField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationCreditLimitsMaxBetLimit MaxBetLimit {
            get {
                return this.maxBetLimitField;
            }
            set {
                this.maxBetLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AllowCreditsInAboveMaxCredit {
            get {
                return this.allowCreditsInAboveMaxCreditField;
            }
            set {
                this.allowCreditsInAboveMaxCreditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationCreditLimitsMaxCreditMeter {
        
        private long defaultField;
        
        private long maxAllowedField;
        
        private bool showMessageWhenCreditLimitReachedField;
        
        private bool disableBankNoteAcceptorWhenCreditLimitReachedField;
        
        public AccountingConfigurationCreditLimitsMaxCreditMeter() {
            this.defaultField = ((long)(9223372036854775807));
            this.maxAllowedField = ((long)(9223372036854775807));
            this.showMessageWhenCreditLimitReachedField = false;
            this.disableBankNoteAcceptorWhenCreditLimitReachedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "9223372036854775807")]
        public long Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "9223372036854775807")]
        public long MaxAllowed {
            get {
                return this.maxAllowedField;
            }
            set {
                this.maxAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShowMessageWhenCreditLimitReached {
            get {
                return this.showMessageWhenCreditLimitReachedField;
            }
            set {
                this.showMessageWhenCreditLimitReachedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DisableBankNoteAcceptorWhenCreditLimitReached {
            get {
                return this.disableBankNoteAcceptorWhenCreditLimitReachedField;
            }
            set {
                this.disableBankNoteAcceptorWhenCreditLimitReachedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationCreditLimitsMaxBetLimit {
        
        private long defaultField;
        
        private bool editableField;
        
        private long limitMaxField;
        
        public AccountingConfigurationCreditLimitsMaxBetLimit() {
            this.defaultField = ((long)(10000000000));
            this.editableField = false;
            this.limitMaxField = ((long)(9223372036854775807));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "10000000000")]
        public long Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "9223372036854775807")]
        public long LimitMax {
            get {
                return this.limitMaxField;
            }
            set {
                this.limitMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationWinLimits {
        
        private AccountingConfigurationWinLimitsLargeWinLimit largeWinLimitField;
        
        private AccountingConfigurationWinLimitsLargeWinRatio largeWinRatioField;
        
        private AccountingConfigurationWinLimitsLargeWinRatioThreshold largeWinRatioThresholdField;
        
        private AccountingConfigurationWinLimitsHandpayResetOptions handpayResetOptionsField;
        
        private long handpayLimitField;
        
        private long celebrationLockupLimitField;
        
        public AccountingConfigurationWinLimits() {
            this.handpayLimitField = ((long)(999999999900000));
            this.celebrationLockupLimitField = ((long)(0));
        }
        
        /// <remarks/>
        public AccountingConfigurationWinLimitsLargeWinLimit LargeWinLimit {
            get {
                return this.largeWinLimitField;
            }
            set {
                this.largeWinLimitField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationWinLimitsLargeWinRatio LargeWinRatio {
            get {
                return this.largeWinRatioField;
            }
            set {
                this.largeWinRatioField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationWinLimitsLargeWinRatioThreshold LargeWinRatioThreshold {
            get {
                return this.largeWinRatioThresholdField;
            }
            set {
                this.largeWinRatioThresholdField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationWinLimitsHandpayResetOptions HandpayResetOptions {
            get {
                return this.handpayResetOptionsField;
            }
            set {
                this.handpayResetOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "999999999900000")]
        public long HandpayLimit {
            get {
                return this.handpayLimitField;
            }
            set {
                this.handpayLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long CelebrationLockupLimit {
            get {
                return this.celebrationLockupLimitField;
            }
            set {
                this.celebrationLockupLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationWinLimitsLargeWinLimit {
        
        private long defaultField;
        
        private long maxAllowedField;
        
        private bool editableField;
        
        private bool overrideTransactionNameField;
        
        public AccountingConfigurationWinLimitsLargeWinLimit() {
            this.defaultField = ((long)(999999999900000));
            this.maxAllowedField = ((long)(999999999900000));
            this.editableField = true;
            this.overrideTransactionNameField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "999999999900000")]
        public long Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "999999999900000")]
        public long MaxAllowed {
            get {
                return this.maxAllowedField;
            }
            set {
                this.maxAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OverrideTransactionName {
            get {
                return this.overrideTransactionNameField;
            }
            set {
                this.overrideTransactionNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationWinLimitsLargeWinRatio {
        
        private long defaultField;
        
        private bool editableField;
        
        private bool visibleField;
        
        public AccountingConfigurationWinLimitsLargeWinRatio() {
            this.defaultField = ((long)(0));
            this.editableField = false;
            this.visibleField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationWinLimitsLargeWinRatioThreshold {
        
        private long defaultField;
        
        private bool editableField;
        
        private bool visibleField;
        
        public AccountingConfigurationWinLimitsLargeWinRatioThreshold() {
            this.defaultField = ((long)(0));
            this.editableField = false;
            this.visibleField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationWinLimitsHandpayResetOptions {
        
        private bool visibleField;
        
        public AccountingConfigurationWinLimitsHandpayResetOptions() {
            this.visibleField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationNoteIn {
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationVoucherIn {
        
        private string stateField;
        
        private bool enableLimitField;
        
        private long limitDefaultField;
        
        private long limitMaxField;
        
        private bool allowLimitEditField;
        
        public AccountingConfigurationVoucherIn() {
            this.enableLimitField = true;
            this.limitDefaultField = ((long)(9223372036854775807));
            this.limitMaxField = ((long)(9223372036854775807));
            this.allowLimitEditField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool EnableLimit {
            get {
                return this.enableLimitField;
            }
            set {
                this.enableLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "9223372036854775807")]
        public long LimitDefault {
            get {
                return this.limitDefaultField;
            }
            set {
                this.limitDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "9223372036854775807")]
        public long LimitMax {
            get {
                return this.limitMaxField;
            }
            set {
                this.limitMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool AllowLimitEdit {
            get {
                return this.allowLimitEditField;
            }
            set {
                this.allowLimitEditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationVoucherOut {
        
        private AccountingConfigurationVoucherOutExpiration expirationField;
        
        private string stateField;
        
        private bool enableLimitField;
        
        private long limitDefaultField;
        
        private bool allowCashWinTicketField;
        
        private string allowNonCashableTicketField;
        
        private bool offlineField;
        
        private long limitMaxField;
        
        private bool allowLimitEditField;
        
        private bool separateMeteringCashableAndPromoAmountsField;
        
        private long maxSequenceField;
        
        public AccountingConfigurationVoucherOut() {
            this.enableLimitField = true;
            this.limitDefaultField = ((long)(9223372036854775807));
            this.allowCashWinTicketField = false;
            this.allowNonCashableTicketField = "Disabled";
            this.offlineField = false;
            this.limitMaxField = ((long)(9223372036854775807));
            this.allowLimitEditField = true;
            this.separateMeteringCashableAndPromoAmountsField = false;
            this.maxSequenceField = ((long)(9999));
        }
        
        /// <remarks/>
        public AccountingConfigurationVoucherOutExpiration Expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool EnableLimit {
            get {
                return this.enableLimitField;
            }
            set {
                this.enableLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "9223372036854775807")]
        public long LimitDefault {
            get {
                return this.limitDefaultField;
            }
            set {
                this.limitDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AllowCashWinTicket {
            get {
                return this.allowCashWinTicketField;
            }
            set {
                this.allowCashWinTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Disabled")]
        public string AllowNonCashableTicket {
            get {
                return this.allowNonCashableTicketField;
            }
            set {
                this.allowNonCashableTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Offline {
            get {
                return this.offlineField;
            }
            set {
                this.offlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "9223372036854775807")]
        public long LimitMax {
            get {
                return this.limitMaxField;
            }
            set {
                this.limitMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool AllowLimitEdit {
            get {
                return this.allowLimitEditField;
            }
            set {
                this.allowLimitEditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SeparateMeteringCashableAndPromoAmounts {
            get {
                return this.separateMeteringCashableAndPromoAmountsField;
            }
            set {
                this.separateMeteringCashableAndPromoAmountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "9999")]
        public long MaxSequence {
            get {
                return this.maxSequenceField;
            }
            set {
                this.maxSequenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationVoucherOutExpiration {
        
        private int daysField;
        
        private bool editableField;
        
        public AccountingConfigurationVoucherOutExpiration() {
            this.daysField = 30;
            this.editableField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(30)]
        public int Days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationRebootWhilePrinting {
        
        private string behaviorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Behavior {
            get {
                return this.behaviorField;
            }
            set {
                this.behaviorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationReprintLoggedVoucher {
        
        private string behaviorField;
        
        private bool titleOverrideField;
        
        private string doorOpenRequirementField;
        
        public AccountingConfigurationReprintLoggedVoucher() {
            this.titleOverrideField = false;
            this.doorOpenRequirementField = "None";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Behavior {
            get {
                return this.behaviorField;
            }
            set {
                this.behaviorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool TitleOverride {
            get {
                return this.titleOverrideField;
            }
            set {
                this.titleOverrideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("None")]
        public string DoorOpenRequirement {
            get {
                return this.doorOpenRequirementField;
            }
            set {
                this.doorOpenRequirementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationHandpay {
        
        private AccountingConfigurationHandpayRemoteHandpayReset remoteHandpayResetField;
        
        private AccountingConfigurationHandpayPrintHandpayReceipt printHandpayReceiptField;
        
        private AccountingConfigurationHandpayAllowGameWinReceipt allowGameWinReceiptField;
        
        private bool noteAcceptorConnectedRequiredField;
        
        private bool largeWinForcedKeyOffField;
        
        private KeyOffType largeWinKeyOffStrategyField;
        
        private bool handpayPendingExitEnabledField;
        
        private bool canKeyOffWhileInLockUpField;
        
        private bool handpayReceiptsRequiredField;
        
        public AccountingConfigurationHandpay() {
            this.noteAcceptorConnectedRequiredField = false;
            this.largeWinForcedKeyOffField = false;
            this.largeWinKeyOffStrategyField = KeyOffType.LocalHandpay;
            this.handpayPendingExitEnabledField = false;
            this.canKeyOffWhileInLockUpField = true;
            this.handpayReceiptsRequiredField = false;
        }
        
        /// <remarks/>
        public AccountingConfigurationHandpayRemoteHandpayReset RemoteHandpayReset {
            get {
                return this.remoteHandpayResetField;
            }
            set {
                this.remoteHandpayResetField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationHandpayPrintHandpayReceipt PrintHandpayReceipt {
            get {
                return this.printHandpayReceiptField;
            }
            set {
                this.printHandpayReceiptField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationHandpayAllowGameWinReceipt AllowGameWinReceipt {
            get {
                return this.allowGameWinReceiptField;
            }
            set {
                this.allowGameWinReceiptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool NoteAcceptorConnectedRequired {
            get {
                return this.noteAcceptorConnectedRequiredField;
            }
            set {
                this.noteAcceptorConnectedRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool LargeWinForcedKeyOff {
            get {
                return this.largeWinForcedKeyOffField;
            }
            set {
                this.largeWinForcedKeyOffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(KeyOffType.LocalHandpay)]
        public KeyOffType LargeWinKeyOffStrategy {
            get {
                return this.largeWinKeyOffStrategyField;
            }
            set {
                this.largeWinKeyOffStrategyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool HandpayPendingExitEnabled {
            get {
                return this.handpayPendingExitEnabledField;
            }
            set {
                this.handpayPendingExitEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool CanKeyOffWhileInLockUp {
            get {
                return this.canKeyOffWhileInLockUpField;
            }
            set {
                this.canKeyOffWhileInLockUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool HandpayReceiptsRequired {
            get {
                return this.handpayReceiptsRequiredField;
            }
            set {
                this.handpayReceiptsRequiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationHandpayRemoteHandpayReset {
        
        private bool allowedField;
        
        private bool configurableField;
        
        public AccountingConfigurationHandpayRemoteHandpayReset() {
            this.allowedField = true;
            this.configurableField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Allowed {
            get {
                return this.allowedField;
            }
            set {
                this.allowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Configurable {
            get {
                return this.configurableField;
            }
            set {
                this.configurableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationHandpayPrintHandpayReceipt {
        
        private bool enabledField;
        
        private bool editableField;
        
        public AccountingConfigurationHandpayPrintHandpayReceipt() {
            this.enabledField = false;
            this.editableField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationHandpayAllowGameWinReceipt {
        
        private bool enabledField;
        
        public AccountingConfigurationHandpayAllowGameWinReceipt() {
            this.enabledField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum KeyOffType {
        
        /// <remarks/>
        LocalHandpay,
        
        /// <remarks/>
        LocalVoucher,
        
        /// <remarks/>
        LocalWat,
        
        /// <remarks/>
        LocalCredit,
        
        /// <remarks/>
        RemoteHandpay,
        
        /// <remarks/>
        RemoteVoucher,
        
        /// <remarks/>
        RemoteWat,
        
        /// <remarks/>
        RemoteCredit,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationHandCount {
        
        private AccountingConfigurationHandCountHandCountPayoutLimit handCountPayoutLimitField;
        
        private AccountingConfigurationHandCountBillAcceptanceLimit billAcceptanceLimitField;
        
        private bool handCountServiceEnabledField;
        
        private long cashoutAmountPerHandCountField;
        
        private long handCountResetCreditLimitField;
        
        public AccountingConfigurationHandCount() {
            this.handCountServiceEnabledField = false;
            this.cashoutAmountPerHandCountField = ((long)(500000));
            this.handCountResetCreditLimitField = ((long)(25000));
        }
        
        /// <remarks/>
        public AccountingConfigurationHandCountHandCountPayoutLimit HandCountPayoutLimit {
            get {
                return this.handCountPayoutLimitField;
            }
            set {
                this.handCountPayoutLimitField = value;
            }
        }
        
        /// <remarks/>
        public AccountingConfigurationHandCountBillAcceptanceLimit BillAcceptanceLimit {
            get {
                return this.billAcceptanceLimitField;
            }
            set {
                this.billAcceptanceLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool HandCountServiceEnabled {
            get {
                return this.handCountServiceEnabledField;
            }
            set {
                this.handCountServiceEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "500000")]
        public long CashoutAmountPerHandCount {
            get {
                return this.cashoutAmountPerHandCountField;
            }
            set {
                this.cashoutAmountPerHandCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "25000")]
        public long HandCountResetCreditLimit {
            get {
                return this.handCountResetCreditLimitField;
            }
            set {
                this.handCountResetCreditLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationHandCountHandCountPayoutLimit {
        
        private bool visibleField;
        
        private bool configurableField;
        
        private long limitDefaultField;
        
        public AccountingConfigurationHandCountHandCountPayoutLimit() {
            this.visibleField = false;
            this.configurableField = false;
            this.limitDefaultField = ((long)(9223372036854775807));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Configurable {
            get {
                return this.configurableField;
            }
            set {
                this.configurableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "9223372036854775807")]
        public long LimitDefault {
            get {
                return this.limitDefaultField;
            }
            set {
                this.limitDefaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationHandCountBillAcceptanceLimit {
        
        private bool visibleField;
        
        public AccountingConfigurationHandCountBillAcceptanceLimit() {
            this.visibleField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationMysteryProgressive {
        
        private bool winAsExternalBonusField;
        
        public AccountingConfigurationMysteryProgressive() {
            this.winAsExternalBonusField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool WinAsExternalBonus {
            get {
                return this.winAsExternalBonusField;
            }
            set {
                this.winAsExternalBonusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationCashoutOnCarrierBoardRemoval {
        
        private bool enabledField;
        
        public AccountingConfigurationCashoutOnCarrierBoardRemoval() {
            this.enabledField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationNoteAcceptorTimeLimit {
        
        private bool enableField;
        
        private int valueField;
        
        public AccountingConfigurationNoteAcceptorTimeLimit() {
            this.enableField = false;
            this.valueField = 5000;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(5000)]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationBillClearance {
        
        private bool enabledField;
        
        public AccountingConfigurationBillClearance() {
            this.enabledField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AccountingConfigurationTestTicket {
        
        private string typeField;
        
        public AccountingConfigurationTestTicket() {
            this.typeField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
}
#pragma warning restore CS1591
