//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class BrowserConfiguration {
    
    private BrowserConfigurationBrowser browserField;
    
    /// <remarks/>
    public BrowserConfigurationBrowser Browser {
        get {
            return this.browserField;
        }
        set {
            this.browserField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BrowserConfigurationBrowser {
    
    private double maxCpuPerProcessField;
    
    private double maxCpuTotalField;
    
    private double maxMemoryPerProcessField;

    /// <remarks/>
    public BrowserConfigurationBrowser() {
        this.maxCpuPerProcessField = 25D;
        this.maxCpuTotalField = 50D;
        this.maxMemoryPerProcessField = 500D;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(25D)]
    public double MaxCpuPerProcess {
        get {
            return this.maxCpuPerProcessField;
        }
        set {
            this.maxCpuPerProcessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(50D)]
    public double MaxCpuTotal {
        get {
            return this.maxCpuTotalField;
        }
        set {
            this.maxCpuTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(500D)]
    public double MaxMemoryPerProcess {
        get {
            return this.maxMemoryPerProcessField;
        }
        set {
            this.maxMemoryPerProcessField = value;
        }
    }
}
