namespace Aristocrat.Sas.Client
{
    public enum BillDenominationCodes
    {
        One,
        Two,
        Five,
        Ten,
        Twenty,
        TwentyFive,
        Fifty,
        OneHundred,
        TwoHundred,
        TwoHundredFifty,
        FiveHundred,
        OneThousand,
        TwoThousand,
        TwoThousandFiveHundred,
        FiveThousand,
        TenThousand,
        TwentyThousand,
        TwentyFiveThousand,
        FiftyThousand,
        OneHundredThousand,
        TwoHundredThousand,
        TwoHundredFiftyThousand,
        FiveHundredThousand,
        OneMillion
    }
}