namespace Aristocrat.Sas.Client
{
    using System.Collections.Generic;

    internal class LongPollTable
    {
        private LongPollTable() { }

        /// <summary>
        ///    LONG_POLL table includes length and flag for optional length byte
        /// </summary>
        internal static List<(byte length, bool isVariableLength, bool worksWithGlobalPolls)> Rows =
            new List<(byte length, bool isVariableLength, bool worksWithGlobalPolls)>()
        {
		    // length,  length byte,  global
		    ( 2, false, false ), // 0x00
		    ( 4, false, false ), // 0x01
		    ( 4, false, false ), // 0x02
		    ( 4, false, false ), // 0x03
		    ( 4, false, false ), // 0x04
		    ( 4, false, false ), // 0x05
		    ( 4, false, false ), // 0x06
		    ( 4, false, false ), // 0x07
		    ( 9, false, false ), // 0x08
		    ( 7, false, false ), // 0x09
		    ( 4, false, false ), // 0x0A
		    ( 4, false, false ), // 0x0B
		    ( 0, false, false ), // 0x0C
		    ( 0, false, false ), // 0x0D
		    ( 5, false, false ), // 0x0E
		    ( 2, false, false ), // 0x0F
		    ( 2, false, false ), // 0x10
		    ( 2, false, false ), // 0x11
		    ( 2, false, false ), // 0x12
		    ( 2, false, false ), // 0x13
		    ( 2, false, false ), // 0x14
		    ( 2, false, false ), // 0x15
		    ( 2, false, false ), // 0x16
		    ( 2, false, false ), // 0x17
		    ( 2, false, false ), // 0x18
		    ( 2, false, false ), // 0x19
		    ( 2, false, false ), // 0x1A
		    ( 2, false, false ), // 0x1B
		    ( 2, false, false ), // 0x1C
		    ( 2, false, false ), // 0x1D
		    ( 2, false, false ), // 0x1E
		    ( 2, false, false ), // 0x1F
		    ( 2, false, false ), // 0x20
		    ( 6, false, false ), // 0x21
		    ( 2, false, false ), // 0x22
		    ( 2, false, false ), // 0x23
		    ( 2, false, false ), // 0x24
		    ( 2, false, false ), // 0x25
		    ( 2, false, false ), // 0x26
		    ( 2, false, false ), // 0x27
		    ( 2, false, false ), // 0x28
		    ( 2, false, false ), // 0x29
		    ( 2, false, false ), // 0x2A
		    ( 2, false, false ), // 0x2B
		    ( 2, false, false ), // 0x2C
		    ( 6, false, false ), // 0x2D
		    ( 6, false, false ), // 0x2E
		    ( 5, true, false ), // 0x2F
		    ( 2, false, false ), // 0x30
		    ( 2, false, false ), // 0x31
		    ( 2, false, false ), // 0x32
		    ( 2, false, false ), // 0x33
		    ( 2, false, false ), // 0x34
		    ( 2, false, false ), // 0x35
		    ( 2, false, false ), // 0x36
		    ( 2, false, false ), // 0x37
		    ( 2, false, false ), // 0x38
		    ( 2, false, false ), // 0x39
		    ( 2, false, false ), // 0x3A
		    ( 2, false, false ), // 0x3B
		    ( 2, false, false ), // 0x3C
		    ( 2, false, false ), // 0x3D
		    ( 2, false, false ), // 0x3E
            ( 2, false, false ), // 0x3F
            ( 2, false, false ), // 0x40
            ( 2, false, false ), // 0x41
		    ( 2, false, false ), // 0x42
		    ( 2, false, false ), // 0x43
		    ( 2, false, false ), // 0x44
		    ( 2, false, false ), // 0x45
		    ( 2, false, false ), // 0x46
		    ( 2, false, false ), // 0x47
		    ( 2, false, false ), // 0x48
		    ( 2, false, false ), // 0x49
		    ( 2, false, false ), // 0x4A
		    ( 2, false, false ), // 0x4B
		    ( 10, false, false ), // 0x4C
		    ( 5, false, false ), // 0x4D
		    ( 2, false, false ), // 0x4E
		    ( 2, false, false ), // 0x4F
		    ( 5, false, false ), // 0x50
		    ( 2, false, false ), // 0x51
		    ( 6, false, false ), // 0x52
		    ( 6, false, false ), // 0x53
		    ( 2, false, false ), // 0x54
		    ( 2, false, false ), // 0x55
		    ( 2, false, false ), // 0x56
		    ( 2, false, false ), // 0x57
		    ( 13, false, false ), // 0x58
		    ( 2, false, false ), // 0x59
		    ( 2, false, false ), // 0x5A
		    ( 2, false, false ), // 0x5B
		    ( 2, false, false ), // 0x5C
		    ( 2, false, false ), // 0x5D
		    ( 2, false, false ), // 0x5E
		    ( 8, false, false ), // 0x5F
		    ( 2, false, false ), // 0x60
		    ( 2, false, false ), // 0x61
		    ( 10, false, false ), // 0x62
		    ( 10, false, false ), // 0x63
		    ( 6, false, false ), // 0x64
		    ( 6, false, false ), // 0x65
		    ( 5, false, false ), // 0x66
		    ( 2, false, false ), // 0x67
		    ( 2, false, false ), // 0x68
		    ( 10, false, false ), // 0x69
		    ( 2, false, false ), // 0x6A
		    ( 6, false, false ), // 0x6B
		    ( 2, false, false ), // 0x6C
		    ( 2, false, false ), // 0x6D
		    ( 5, true, false ), // 0x6E
		    ( 5, true, false ), // 0x6F
		    ( 2, false, false ), // 0x70
		    ( 5, true, false ), // 0x71
		    ( 5, true, false ), // 0x72
		    ( 5, true, false ), // 0x73
		    ( 8, false, false ), // 0x74
		    ( 5, true, true ), // 0x75
		    ( 5, true, false ), // 0x76
		    ( 9, false, false ), // 0x77
		    ( 2, false, false ), // 0x78
		    ( 2, false, false ), // 0x79
		    ( 5, true, true ), // 0x7A
		    ( 5, true, true ), // 0x7B
		    ( 5, true, true ), // 0x7C
		    ( 5, true, true ), // 0x7D
		    ( 2, false, false ), // 0x7E
		    ( 11, false, true ), // 0x7F
		    ( 11, false, true ), // 0x80
		    ( 2, false, false ), // 0x81
		    ( 2, false, false ), // 0x82
		    ( 6, false, false ), // 0x83
		    ( 2, false, false ), // 0x84
		    ( 2, false, false ), // 0x85
		    ( 5, true, true ), // 0x86
		    ( 2, false, false ), // 0x87
		    ( 2, false, false ), // 0x88
		    ( 2, false, false ), // 0x89
		    ( 9, false, false ), // 0x8A
		    ( 15, false, false ), // 0x8B
		    ( 13, false, false ), // 0x8C
		    ( 2, false, false ), // 0x8D
		    ( 2, false, false ), // 0x8E
		    ( 2, false, false ), // 0x8F
		    ( 2, false, false ), // 0x90
		    ( 2, false, false ), // 0x91
		    ( 2, false, false ), // 0x92
		    ( 2, false, false ), // 0x93
		    ( 4, false, false ), // 0x94
		    ( 6, false, false ), // 0x95
		    ( 6, false, false ), // 0x96
		    ( 6, false, false ), // 0x97
		    ( 6, false, false ), // 0x98
		    ( 6, false, false ), // 0x99
		    ( 6, false, false ), // 0x9A
		    ( 2, false, false ), // 0x9B
		    ( 2, false, false ), // 0x9C
		    ( 2, false, false ), // 0x9D
		    ( 2, false, false ), // 0x9E
		    ( 2, false, false ), // 0x9F
		    ( 6, false, false ), // 0xA0
		    ( 2, false, false ), // 0xA1
		    ( 2, false, false ), // 0xA2
		    ( 2, false, false ), // 0xA3
		    ( 6, false, false ), // 0xA4
		    ( 2, false, false ), // 0xA5
		    ( 2, false, false ), // 0xA6
		    ( 2, false, false ), // 0xA7
		    ( 5, false, false ), // 0xA8
		    ( 2, false, false ), // 0xA9
		    ( 5, false, false ), // 0xAA
		    ( 2, false, false ), // 0xAB
		    ( 2, false, false ), // 0xAC
		    ( 2, false, false ), // 0xAD
		    ( 2, false, false ), // 0xAE
		    ( 5, true, false ), // 0xAF
		    ( 5, true, false ), // 0xB0
		    ( 2, false, false ), // 0xB1
		    ( 2, false, false ), // 0xB2
		    ( 2, false, false ), // 0xB3
		    ( 8, false, false ), // 0xB4
		    ( 6, false, false ), // 0xB5
		    ( 6, false, false ), // 0xB6
		    ( 5, true, false ), // 0xB7
		    ( 2, false, false ), // 0xB8
		    ( 2, false, false ), // 0xB9
		    ( 2, false, false ), // 0xBA
		    ( 2, false, false ), // 0xBB
		    ( 2, false, false ), // 0xBC
		    ( 2, false, false ), // 0xBD
		    ( 2, false, false ), // 0xBE
		    ( 2, false, false ), // 0xBF
		    ( 2, false, false ), // 0xC0
		    ( 2, false, false ), // 0xC1
		    ( 2, false, false ), // 0xC2
		    ( 2, false, false ), // 0xC3
		    ( 2, false, false ), // 0xC4
		    ( 2, false, false ), // 0xC5
		    ( 2, false, false ), // 0xC6
		    ( 2, false, false ), // 0xC7
		    ( 2, false, false ), // 0xC8
		    ( 2, false, false ), // 0xC9
		    ( 2, false, false ), // 0xCA
		    ( 2, false, false ), // 0xCB
		    ( 2, false, false ), // 0xCC
		    ( 2, false, false ), // 0xCD
		    ( 2, false, false ), // 0xCE
		    ( 2, false, false ), // 0xCF
		    ( 2, false, false ), // 0xD0
		    ( 2, false, false ), // 0xD1
		    ( 2, false, false ), // 0xD2
		    ( 2, false, false ), // 0xD3
		    ( 2, false, false ), // 0xD4
		    ( 2, false, false ), // 0xD5
		    ( 2, false, false ), // 0xD6
		    ( 2, false, false ), // 0xD7
		    ( 2, false, false ), // 0xD8
		    ( 2, false, false ), // 0xD9
		    ( 2, false, false ), // 0xDA
		    ( 2, false, false ), // 0xDB
		    ( 2, false, false ), // 0xDC
		    ( 2, false, false ), // 0xDD
		    ( 2, false, false ), // 0xDE
		    ( 2, false, false ), // 0xDF
		    ( 2, false, false ), // 0xE0
		    ( 2, false, false ), // 0xE1
		    ( 2, false, false ), // 0xE2
		    ( 2, false, false ), // 0xE3
		    ( 2, false, false ), // 0xE4
		    ( 2, false, false ), // 0xE5
		    ( 2, false, false ), // 0xE6
		    ( 2, false, false ), // 0xE7
		    ( 2, false, false ), // 0xE8
		    ( 2, false, false ), // 0xE9
		    ( 2, false, false ), // 0xEA
		    ( 2, false, false ), // 0xEB
		    ( 2, false, false ), // 0xEC
		    ( 2, false, false ), // 0xED
		    ( 2, false, false ), // 0xEE
		    ( 2, false, false ), // 0xEF
		    ( 2, false, false ), // 0xF0
		    ( 2, false, false ), // 0xF1
		    ( 2, false, false ), // 0xF2
		    ( 2, false, false ), // 0xF3
		    ( 2, false, false ), // 0xF4
		    ( 2, false, false ), // 0xF5
		    ( 2, false, false ), // 0xF6
		    ( 2, false, false ), // 0xF7
		    ( 2, false, false ), // 0xF8
		    ( 2, false, false ), // 0xF9
		    ( 2, false, false ), // 0xFA
		    ( 2, false, false ), // 0xFB
		    ( 2, false, false ), // 0xFC
		    ( 2, false, false ), // 0xFD
		    ( 2, false, false ), // 0xFE
            ( 2, false, false ), // 0xFF
        };
    }
}
