//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aristocrat.Monaco.Localization.Overrides {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_RhodeIsland {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_RhodeIsland() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aristocrat.Monaco.Localization.Overrides.Resources_RhodeIsland", typeof(Resources_RhodeIsland).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASHOUT VOUCHER.
        /// </summary>
        internal static string CashwinTicket {
            get {
                return ResourceManager.GetString("CashwinTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASHOUT VOUCHER REPRINT.
        /// </summary>
        internal static string CashwinTicketReprint {
            get {
                return ResourceManager.GetString("CashwinTicketReprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASHOUT VOUCHER.
        /// </summary>
        internal static string HandpayReceipt {
            get {
                return ResourceManager.GetString("HandpayReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASHOUT VOUCHER.
        /// </summary>
        internal static string HandpayTicket {
            get {
                return ResourceManager.GetString("HandpayTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JACKPOT VOUCHER.
        /// </summary>
        internal static string JackpotHandpayTicket {
            get {
                return ResourceManager.GetString("JackpotHandpayTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JACKPOT VOUCHER REPRINT.
        /// </summary>
        internal static string JackpotHandpayTicketReprint {
            get {
                return ResourceManager.GetString("JackpotHandpayTicketReprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NeverExpires {
            get {
                return ResourceManager.GetString("NeverExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Voucher....
        /// </summary>
        internal static string PrintHandPayText {
            get {
                return ResourceManager.GetString("PrintHandPayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher #.
        /// </summary>
        internal static string ReceiptSequenceNumber {
            get {
                return ResourceManager.GetString("ReceiptSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VoucherTicketsCreatorNeverExpires {
            get {
                return ResourceManager.GetString("VoucherTicketsCreatorNeverExpires", resourceCulture);
            }
        }
    }
}
