//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class IOConfigurations {
    
    private IOConfigurationsButton[] buttonsField;
    
    private IOConfigurationsKeySwitch[] keySwitchesField;
    
    private IOConfigurationsDoor[] doorsField;
    
    private IOConfigurationsLight[] lightsField;
    
    private IOConfigurationsHardMeters hardMetersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Button", IsNullable=false)]
    public IOConfigurationsButton[] Buttons {
        get {
            return this.buttonsField;
        }
        set {
            this.buttonsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("KeySwitch", IsNullable=false)]
    public IOConfigurationsKeySwitch[] KeySwitches {
        get {
            return this.keySwitchesField;
        }
        set {
            this.keySwitchesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Door", IsNullable=false)]
    public IOConfigurationsDoor[] Doors {
        get {
            return this.doorsField;
        }
        set {
            this.doorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Light", IsNullable=false)]
    public IOConfigurationsLight[] Lights {
        get {
            return this.lightsField;
        }
        set {
            this.lightsField = value;
        }
    }
    
    /// <remarks/>
    public IOConfigurationsHardMeters HardMeters {
        get {
            return this.hardMetersField;
        }
        set {
            this.hardMetersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IOConfigurationsButton : c_logicalDevice {
    
    private int lampBitField;
    /// <remarks/>    
    public IOConfigurationsButton() {
        this.lampBitField = -1;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(-1)]
    public int LampBit {
        get {
            return this.lampBitField;
        }
        set {
            this.lampBitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class c_logicalDevice {
    
    private int physicalIdField;
    
    private int logicalIdField;
    
    private string nameField;
    
    private bool enabledField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PhysicalId {
        get {
            return this.physicalIdField;
        }
        set {
            this.physicalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int LogicalId {
        get {
            return this.logicalIdField;
        }
        set {
            this.logicalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IOConfigurationsKeySwitch : c_logicalDevice {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IOConfigurationsDoor : c_logicalDevice {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IOConfigurationsLight : c_logicalDevice {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IOConfigurationsHardMeters {
    
    private IOConfigurationsHardMetersHardMeter[] hardMeterField;
    
    private long defaultTickValueField;
    /// <remarks/>
    public IOConfigurationsHardMeters() {
        this.defaultTickValueField = ((long)(100));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HardMeter")]
    public IOConfigurationsHardMetersHardMeter[] HardMeter {
        get {
            return this.hardMeterField;
        }
        set {
            this.hardMeterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(long), "100")]
    public long DefaultTickValue {
        get {
            return this.defaultTickValueField;
        }
        set {
            this.defaultTickValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IOConfigurationsHardMetersHardMeter : c_logicalDevice {
}
