//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SupportedDevices {
    
    private SupportedDevicesDevice[] devicesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Device", IsNullable=false)]
    public SupportedDevicesDevice[] Devices {
        get {
            return this.devicesField;
        }
        set {
            this.devicesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SupportedDevicesDevice : c_device {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class c_device {
    
    private string extensionPathField;
    
    private bool restrictToPortField;
    
    private string[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string nameField;
    
    private string typeField;
    
    private string protocolField;
    
    private string portField;
    
    private string modeField;
    
    private bool enabledField;
    
    private int inspectionTimeoutField;

    /// <remarks/>
    public c_device() {
        this.inspectionTimeoutField = 30000;
    }
    
    /// <remarks/>
    public string ExtensionPath {
        get {
            return this.extensionPathField;
        }
        set {
            this.extensionPathField = value;
        }
    }
    
    /// <remarks/>
    public bool RestrictToPort {
        get {
            return this.restrictToPortField;
        }
        set {
            this.restrictToPortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BaudRate", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("DataBits", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Handshake", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Parity", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("StopBits", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("USBClassGUID", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("USBProductId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("USBProductIdDfu", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("USBVendorId", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Protocol {
        get {
            return this.protocolField;
        }
        set {
            this.protocolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(30000)]
    public int InspectionTimeout {
        get {
            return this.inspectionTimeoutField;
        }
        set {
            this.inspectionTimeoutField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    BaudRate,
    
    /// <remarks/>
    DataBits,
    
    /// <remarks/>
    Handshake,
    
    /// <remarks/>
    Parity,
    
    /// <remarks/>
    StopBits,
    
    /// <remarks/>
    USBClassGUID,
    
    /// <remarks/>
    USBProductId,
    
    /// <remarks/>
    USBProductIdDfu,
    
    /// <remarks/>
    USBVendorId,
}
