//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace Aristocrat.Monaco.Mgam.Common.Configuration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MgamConfiguration {
        
        private bool validateServerCertificateField;
        
        private MgamConfigurationCertificateAuthority certificateAuthorityField;
        
        public MgamConfiguration() {
            this.validateServerCertificateField = false;
        }
        
        /// <remarks/>
        public bool ValidateServerCertificate {
            get {
                return this.validateServerCertificateField;
            }
            set {
                this.validateServerCertificateField = value;
            }
        }
        
        /// <remarks/>
        public MgamConfigurationCertificateAuthority CertificateAuthority {
            get {
                return this.certificateAuthorityField;
            }
            set {
                this.certificateAuthorityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MgamConfigurationCertificateAuthority {
        
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
}
