name: 'PR Checks'
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(?<issue>(?:TXM)-\d+)\s+(?<comment>.*?)$'

  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(?<type>[a-z]+)\/(?<issue>(?:TXM)-\d+)(?:-[a-zA-Z0-9]+)?$'
          allowed_prefixes: 'feature'
          ignore: main,develop,candidate
          max_length: 50
