//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
#pragma warning disable CS1591
// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SoundConfiguration {
    
    private SoundConfigurationAudioFiles audioFilesField;
    
    /// <remarks/>
    public SoundConfigurationAudioFiles AudioFiles {
        get {
            return this.audioFilesField;
        }
        set {
            this.audioFilesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SoundConfigurationAudioFiles {
    
    private SoundConfigurationAudioFilesAudioFile[] audioFileField;
    
    private string pathField;
    
    public SoundConfigurationAudioFiles() {
        this.pathField = "..\\jurisdiction\\DefaultAssets\\";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AudioFile")]
    public SoundConfigurationAudioFilesAudioFile[] AudioFile {
        get {
            return this.audioFileField;
        }
        set {
            this.audioFileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("..\\jurisdiction\\DefaultAssets\\")]
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SoundConfigurationAudioFilesAudioFile {
    
    private SoundName nameField;
    
    private bool nameFieldSpecified;
    
    private string fileField;
    
    public SoundConfigurationAudioFilesAudioFile() {
        this.fileField = "";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SoundName Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NameSpecified {
        get {
            return this.nameFieldSpecified;
        }
        set {
            this.nameFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum SoundName {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    Alert,
    
    /// <remarks/>
    BallDrop,
    
    /// <remarks/>
    CardFlip,
    
    /// <remarks/>
    Center,
    
    /// <remarks/>
    CoinIn,
    
    /// <remarks/>
    CoinOut,
    
    /// <remarks/>
    Collect,
    
    /// <remarks/>
    CriticalMemoryIntegrityCheck,
    
    /// <remarks/>
    Ding,
    
    /// <remarks/>
    DoorAlarm,
    
    /// <remarks/>
    DiskSpaceMonitorError,
    
    /// <remarks/>
    ExcessiveDocumentReject,
    
    /// <remarks/>
    ExcessiveMeterIncrement,
    
    /// <remarks/>
    FeatureBell,
    
    /// <remarks/>
    PaperInChute,
    
    /// <remarks/>
    FirmwareCrcError,
    
    /// <remarks/>
    FrontLeft,
    
    /// <remarks/>
    FrontRight,
    
    /// <remarks/>
    HostOffline,
    
    /// <remarks/>
    LowFrequency,
    
    /// <remarks/>
    LiveAuthenticationFailed,
    
    /// <remarks/>
    NoteAcceptorError,
    
    /// <remarks/>
    MoneyLaunderingMonitor,
    
    /// <remarks/>
    PrinterError,
    
    /// <remarks/>
    PrinterWarning,
    
    /// <remarks/>
    RearLeft,
    
    /// <remarks/>
    RearRight,
    
    /// <remarks/>
    ReelClick,
    
    /// <remarks/>
    SideLeft,
    
    /// <remarks/>
    SideRight,
    
    /// <remarks/>
    Silence,
    
    /// <remarks/>
    SendPrintTicket,
    
    /// <remarks/>
    Touch,
}
