//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class VolumeSetting {
    
    private VolumeSettingVolumeNode[] masterVolumeSettingsField;
    
    private VolumeSettingScalarNode[] volumeScalarSettingsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("VolumeNode", IsNullable=false)]
    public VolumeSettingVolumeNode[] MasterVolumeSettings {
        get {
            return this.masterVolumeSettingsField;
        }
        set {
            this.masterVolumeSettingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ScalarNode", IsNullable=false)]
    public VolumeSettingScalarNode[] VolumeScalarSettings {
        get {
            return this.volumeScalarSettingsField;
        }
        set {
            this.volumeScalarSettingsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VolumeSettingVolumeNode : i_volumelevel {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class i_volumelevel {
    
    private VolumeLevelSetting keyField;
    
    private float valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VolumeLevelSetting Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum VolumeLevelSetting {
    
    /// <remarks/>
    ExtraLow,
    
    /// <remarks/>
    Low,
    
    /// <remarks/>
    MediumLow,
    
    /// <remarks/>
    Medium,
    
    /// <remarks/>
    MediumHigh,
    
    /// <remarks/>
    High,
    
    /// <remarks/>
    ExtraHigh,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class i_volumescalar {
    
    private VolumeScalarSetting keyField;
    
    private float valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VolumeScalarSetting Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum VolumeScalarSetting {
    
    /// <remarks/>
    Scalar20,
    
    /// <remarks/>
    Scalar40,
    
    /// <remarks/>
    Scalar60,
    
    /// <remarks/>
    Scalar80,
    
    /// <remarks/>
    Scalar100,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VolumeSettingScalarNode : i_volumescalar {
}
