//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Aristocrat.Monaco.Hardware.Serial {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Overrides {
        
        private OverridesOverride[] overrideField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Override")]
        public OverridesOverride[] Override {
            get {
                return this.overrideField;
            }
            set {
                this.overrideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverride {
        
        private OverridesOverrideAuditTickets auditTicketsField;
        
        private OverridesOverrideTemplateChange[] templateChangesField;
        
        private OverridesOverrideReplacements replacementsField;
        
        private OverridesOverrideNewPrinterTemplates newPrinterTemplatesField;
        
        private OverridesOverrideMapping[] printerTemplateMappingsField;
        
        private OverridesOverrideFontOverride[] fontOverridesField;
        
        private string protocolField;
        
        private string firmwareBaseField;
        
        private bool usePrinterDefinedTemplatesField;
        
        public OverridesOverride() {
            this.usePrinterDefinedTemplatesField = false;
        }
        
        /// <remarks/>
        public OverridesOverrideAuditTickets AuditTickets {
            get {
                return this.auditTicketsField;
            }
            set {
                this.auditTicketsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TemplateChange", IsNullable=false)]
        public OverridesOverrideTemplateChange[] TemplateChanges {
            get {
                return this.templateChangesField;
            }
            set {
                this.templateChangesField = value;
            }
        }
        
        /// <remarks/>
        public OverridesOverrideReplacements Replacements {
            get {
                return this.replacementsField;
            }
            set {
                this.replacementsField = value;
            }
        }
        
        /// <remarks/>
        public OverridesOverrideNewPrinterTemplates NewPrinterTemplates {
            get {
                return this.newPrinterTemplatesField;
            }
            set {
                this.newPrinterTemplatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Mapping", IsNullable=false)]
        public OverridesOverrideMapping[] PrinterTemplateMappings {
            get {
                return this.printerTemplateMappingsField;
            }
            set {
                this.printerTemplateMappingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FontOverride", IsNullable=false)]
        public OverridesOverrideFontOverride[] FontOverrides {
            get {
                return this.fontOverridesField;
            }
            set {
                this.fontOverridesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirmwareBase {
            get {
                return this.firmwareBaseField;
            }
            set {
                this.firmwareBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UsePrinterDefinedTemplates {
            get {
                return this.usePrinterDefinedTemplatesField;
            }
            set {
                this.usePrinterDefinedTemplatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideAuditTickets {
        
        private string platformTemplateIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlatformTemplateIds {
            get {
                return this.platformTemplateIdsField;
            }
            set {
                this.platformTemplateIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideTemplateChange {
        
        private string nameField;
        
        private byte platformTemplateIdField;
        
        private string regionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte PlatformTemplateId {
            get {
                return this.platformTemplateIdField;
            }
            set {
                this.platformTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Regions {
            get {
                return this.regionsField;
            }
            set {
                this.regionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideReplacements {
        
        private OverridesOverrideReplacementsGlobalReplace[] globalRegionTextReplaceField;
        
        private OverridesOverrideReplacementsTextReplace[] regionTextReplaceField;
        
        private OverridesOverrideReplacementsChangeRegionCase[] changeRegionCaseField;
        
        private OverridesOverrideReplacementsSplit[] textSplitForRegionField;
        
        private OverridesOverrideReplacementsRegionTextCombine[] textCombineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("GlobalReplace", IsNullable=false)]
        public OverridesOverrideReplacementsGlobalReplace[] GlobalRegionTextReplace {
            get {
                return this.globalRegionTextReplaceField;
            }
            set {
                this.globalRegionTextReplaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TextReplace", IsNullable=false)]
        public OverridesOverrideReplacementsTextReplace[] RegionTextReplace {
            get {
                return this.regionTextReplaceField;
            }
            set {
                this.regionTextReplaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChangeRegionCase")]
        public OverridesOverrideReplacementsChangeRegionCase[] ChangeRegionCase {
            get {
                return this.changeRegionCaseField;
            }
            set {
                this.changeRegionCaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Split", IsNullable=false)]
        public OverridesOverrideReplacementsSplit[] TextSplitForRegion {
            get {
                return this.textSplitForRegionField;
            }
            set {
                this.textSplitForRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RegionTextCombine", IsNullable=false)]
        public OverridesOverrideReplacementsRegionTextCombine[] TextCombine {
            get {
                return this.textCombineField;
            }
            set {
                this.textCombineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideReplacementsGlobalReplace {
        
        private string replaceField;
        
        private string withField;
        
        private bool onlyFirstOccurrencePerLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string With {
            get {
                return this.withField;
            }
            set {
                this.withField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool OnlyFirstOccurrencePerLine {
            get {
                return this.onlyFirstOccurrencePerLineField;
            }
            set {
                this.onlyFirstOccurrencePerLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideReplacementsTextReplace {
        
        private string platformTemplateIdsField;
        
        private string regionIdField;
        
        private string descriptionField;
        
        private string replaceField;
        
        private string withField;
        
        private bool isReplaceRegexStringField;
        
        private string leadingTextField;
        
        public OverridesOverrideReplacementsTextReplace() {
            this.platformTemplateIdsField = "";
            this.leadingTextField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string PlatformTemplateIds {
            get {
                return this.platformTemplateIdsField;
            }
            set {
                this.platformTemplateIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegionId {
            get {
                return this.regionIdField;
            }
            set {
                this.regionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string With {
            get {
                return this.withField;
            }
            set {
                this.withField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsReplaceRegexString {
            get {
                return this.isReplaceRegexStringField;
            }
            set {
                this.isReplaceRegexStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string LeadingText {
            get {
                return this.leadingTextField;
            }
            set {
                this.leadingTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideReplacementsChangeRegionCase {
        
        private string regionIdField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegionId {
            get {
                return this.regionIdField;
            }
            set {
                this.regionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideReplacementsSplit {
        
        private string regionIdField;
        
        private string newRegionIdField;
        
        private string descriptionField;
        
        private string regExField;
        
        private string formatStringField;
        
        private string leadingTextField;
        
        public OverridesOverrideReplacementsSplit() {
            this.regExField = "";
            this.formatStringField = "";
            this.leadingTextField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegionId {
            get {
                return this.regionIdField;
            }
            set {
                this.regionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewRegionId {
            get {
                return this.newRegionIdField;
            }
            set {
                this.newRegionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string RegEx {
            get {
                return this.regExField;
            }
            set {
                this.regExField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string FormatString {
            get {
                return this.formatStringField;
            }
            set {
                this.formatStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string LeadingText {
            get {
                return this.leadingTextField;
            }
            set {
                this.leadingTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideReplacementsRegionTextCombine {
        
        private string platformTemplateIdsField;
        
        private string regionIdsField;
        
        private string newRegionIdField;
        
        private string leadingTextField;
        
        private string joinTextField;
        
        private string trailingTextField;
        
        public OverridesOverrideReplacementsRegionTextCombine() {
            this.leadingTextField = "";
            this.joinTextField = "";
            this.trailingTextField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlatformTemplateIds {
            get {
                return this.platformTemplateIdsField;
            }
            set {
                this.platformTemplateIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegionIds {
            get {
                return this.regionIdsField;
            }
            set {
                this.regionIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewRegionId {
            get {
                return this.newRegionIdField;
            }
            set {
                this.newRegionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string LeadingText {
            get {
                return this.leadingTextField;
            }
            set {
                this.leadingTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string JoinText {
            get {
                return this.joinTextField;
            }
            set {
                this.joinTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string TrailingText {
            get {
                return this.trailingTextField;
            }
            set {
                this.trailingTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideNewPrinterTemplates {
        
        private OverridesOverrideNewPrinterTemplatesNewRegion[] newRegionField;
        
        private OverridesOverrideNewPrinterTemplatesNewTemplate[] newTemplateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewRegion")]
        public OverridesOverrideNewPrinterTemplatesNewRegion[] NewRegion {
            get {
                return this.newRegionField;
            }
            set {
                this.newRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewTemplate")]
        public OverridesOverrideNewPrinterTemplatesNewTemplate[] NewTemplate {
            get {
                return this.newTemplateField;
            }
            set {
                this.newTemplateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideNewPrinterTemplatesNewRegion {
        
        private string descriptionField;
        
        private string printerRegionIdField;
        
        private string commandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PrinterRegionId {
            get {
                return this.printerRegionIdField;
            }
            set {
                this.printerRegionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideNewPrinterTemplatesNewTemplate {
        
        private string descriptionField;
        
        private string printerTemplateIdField;
        
        private string commandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PrinterTemplateId {
            get {
                return this.printerTemplateIdField;
            }
            set {
                this.printerTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideMapping {
        
        private string descriptionField;
        
        private string platformTemplateIdField;
        
        private string printerTemplateIdField;
        
        private string regionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlatformTemplateId {
            get {
                return this.platformTemplateIdField;
            }
            set {
                this.platformTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PrinterTemplateId {
            get {
                return this.printerTemplateIdField;
            }
            set {
                this.printerTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Regions {
            get {
                return this.regionsField;
            }
            set {
                this.regionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OverridesOverrideFontOverride {
        
        private string regionIdsField;
        
        private string originalFontNumberField;
        
        private string newFontNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegionIds {
            get {
                return this.regionIdsField;
            }
            set {
                this.regionIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginalFontNumber {
            get {
                return this.originalFontNumberField;
            }
            set {
                this.originalFontNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewFontNumber {
            get {
                return this.newFontNumberField;
            }
            set {
                this.newFontNumberField = value;
            }
        }
    }
}
