//------------------------------------------------------------------------------
// <auto-generated>
// This file was automatically generated by a tool.
// Schema Format Version: 1.2
// Generator Version: 2.5.0.0
//
// DO NOT MODIFY THIS FILE MANUALLY.
// Changes to this file may cause incorrect behavior and will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Aristocrat.Monaco.Kernel.MarketConfig.Models.Application
{
    /// <summary>
    /// Gaming Runnable Enumeration
    /// </summary>
    public enum GamingRunnableType
    {
        /// <summary>Class 3</summary>
        Class3,
        /// <summary>Class 2</summary>
        Class2,
        /// <summary>VLT</summary>
        VLT
    }

    /// <summary>
    /// Market Jurisdiction Configuration for the Application segment
    /// </summary>
    [MarketConfigSegment("application")]
    public class ApplicationConfigSegment
    {
        /// <summary>
        /// Gaming Runnable
        /// </summary>
        [JsonProperty(PropertyName = "gaming_runnable", Required = Required.Always)]
        public GamingRunnableType GamingRunnable { get; set; }
    }
}