//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Aristocrat.Monaco.Gaming.Contracts.TowerLight {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TowerLightConfiguration {
        
        private SignalDefinitionsType[] signalDefinitionsField;
        
        private string[] tiltDoorsField;
        
        private bool disableTowerLightsField;
        
        public TowerLightConfiguration() {
            this.disableTowerLightsField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SignalDefinitions")]
        public SignalDefinitionsType[] SignalDefinitions {
            get {
                return this.signalDefinitionsField;
            }
            set {
                this.signalDefinitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DoorName", IsNullable=false)]
        public string[] TiltDoors {
            get {
                return this.tiltDoorsField;
            }
            set {
                this.tiltDoorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool disableTowerLights {
            get {
                return this.disableTowerLightsField;
            }
            set {
                this.disableTowerLightsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignalDefinitionsType {
        
        private OperationalConditionType[] operationalConditionField;
        
        private string tierField;
        
        private string updateTowerLightSignalBehaviourField;
        
        public SignalDefinitionsType() {
            this.updateTowerLightSignalBehaviourField = "Default";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperationalCondition")]
        public OperationalConditionType[] OperationalCondition {
            get {
                return this.operationalConditionField;
            }
            set {
                this.operationalConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tier {
            get {
                return this.tierField;
            }
            set {
                this.tierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string UpdateTowerLightSignalBehaviour {
            get {
                return this.updateTowerLightSignalBehaviourField;
            }
            set {
                this.updateTowerLightSignalBehaviourField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperationalConditionType {
        
        private DoorConditionType[] doorConditionField;
        
        private string[] conditionField;
        
        private bool canBeOverriddenByLowerIfOffField;
        
        public OperationalConditionType() {
            this.canBeOverriddenByLowerIfOffField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DoorCondition")]
        public DoorConditionType[] DoorCondition {
            get {
                return this.doorConditionField;
            }
            set {
                this.doorConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool CanBeOverriddenByLowerIfOff {
            get {
                return this.canBeOverriddenByLowerIfOffField;
            }
            set {
                this.canBeOverriddenByLowerIfOffField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoorConditionType {
        
        private SetType[] setField;
        
        private string conditionField;
        
        private bool resetField;
        
        public DoorConditionType() {
            this.resetField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Set")]
        public SetType[] Set {
            get {
                return this.setField;
            }
            set {
                this.setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Reset {
            get {
                return this.resetField;
            }
            set {
                this.resetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetType {
        
        private string lightTierField;
        
        private string flashStateField;
        
        private long durationField;
        
        public SetType() {
            this.durationField = ((long)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lightTier {
            get {
                return this.lightTierField;
            }
            set {
                this.lightTierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flashState {
            get {
                return this.flashStateField;
            }
            set {
                this.flashStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
}

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member