name: Build

on:
  workflow_dispatch:

  push:
    branches:
    - main
    - develop
    - release/*
    paths-ignore:
    - '.github/**'

  pull_request:
    branches:
    - main
    - develop
    - release/*

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        configuration: [Debug, Release, Retail]
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      with:
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.1.1
      with:
        nuget-version: '5.x'
    - name: Cache NuGet Packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
    - name: Setup Monaco Tools
      uses: Aristocrat-Monaco-Platform/actions/setup-monaco@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
        additionalArguments: '/updateassemblyinfo'
    - name: Restore
      run: |
        dotnet restore .\Monaco.sln
    - name: Build
      run: |
        dotnet build -c ${{ matrix.configuration }} --no-restore .\Monaco.sln
    - name: Test
      if: matrix.configuration == 'Debug'
      run: |
        dotnet test --no-build --no-restore -l trx -r TestResults -c Debug --arch x64 .\Monaco.sln
    - name: Test Report
      if: matrix.configuration == 'Debug'
      uses: dorny/test-reporter@v1
      with:
        name: Unit Tests
        path: "**/*.trx"
        reporter: dotnet-trx
        fail-on-error: true
