name: Build

on:
  workflow_dispatch:

  push:
    branches:
    - main
    - release/*

  pull_request:
    branches:
    - main
    - release/*

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        configuration: [Debug, Release, Retail]
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      with:
        dotnet-version: '5.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    - name: Setup msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.0.5
      with:
        nuget-version: '5.x'
    - name: Cache NuGet Packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
    - name: Setup VSTest Path
      if: matrix.configuration == 'Debug'
      uses: darenm/setup-vstest@v1
    - name: Setup Monaco Tools
      uses: Aristocrat-Monaco-Platform/actions/setup-monaco@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        additionalArguments: '/updateassemblyinfo'
    - name: Restore
      run: |
        nuget restore .\Monaco.sln
    - name: Build
      run: |
        msbuild -p:"Configuration=${{ matrix.configuration }}" -p:"Platform=Any CPU" -t:Rebuild .\Monaco.sln
    - name: Test
      if: matrix.configuration == 'Debug'
      run: >
        vstest.console.exe
        "**\bin\Debug\*.Tests.dll"
        --platform:x64
        --logger:trx
        --resultsDirectory:TestResults
        || true
    - name: Test Report
      if: matrix.configuration == 'Debug'
      uses: dorny/test-reporter@v1
      with:
        name: Unit Tests
        path: "**/*.trx"
        reporter: dotnet-trx
        fail-on-error: true
