name: GitHubPages

on:
  workflow_dispatch:

  push:
    branches:
    - main
    - release/*
    paths:
    - 'Accounting/**'
    - 'Application/**'
    - 'Gaming/**'
    - 'Hardware/**'
    - 'Jurisdiction/**'
    - 'Kernel/**'
    - 'Protocol/**'
    - 'Shared/**'
    - 'Documentation/**'

jobs:
  build-docs:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      env:
        NUGET_AUTH_TOKEN: ${{secrets.REGISTRY_TOKEN}}
      with:
        dotnet-version: '5.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    - name: Setup msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Remove TeamCity NuGet Source
      run: >
        dotnet nuget remove source TeamCity --configfile ./NuGet.config
    - name: Cache .nuke/temp, ~/.nuget/packages
      uses: actions/cache@v2
      with:
        path: |
          .nuke/temp
          ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
    - name: Build
      run: ./build.cmd BuildDocs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./bin/Site
        keep_files: true
